server:
  port: 8080
  tomcat:
    max-swallow-size: 10MB
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  main:
    banner-mode: console
logging:
  level:
    root: INFO
    com.example.aadharparserapi: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true


